### PR TITLE
GUI Option, Code Beautified, Adjusted README

### PR DESCRIPTION
**Pull request by HanzHaxors**
I promised to add a GUI option to this repository and so today i work it out and finish it with some bonus. Here's the catch:
 - GUI Cannot be opened in WSL (of course, it isn't supported right now)
 - GUI might never be available in termux. Otherwise, they should use nethunter image first
#### Now the pros:
 - GUI is open sourced and ready to be edited in any given time (through [wxFormBuilder](https://github.com/wxFormBuilder/))
 - GUI is cross-platform

I beautify the code, so anybody can learn or contribute to the project easier

### Tests
 - [x] Windows
 - [ ]  ~~WSL~~
 - [ ] ~~Termux~~

**I could say that this PR is exclusively made for PCs**

### CODE REVIEW

**Comment by HanzHaxors** [comment]
Inspect the first commit meticulously, it's important.

**Comment by HanzHaxors** [comment]
Mind on packing the repo for pip package? That would be great for people who can't do `git clone`

**Comment by TheSpeedX** [comment]
@HanzHaxors  Has this been tested in any PC Linux environment ?

**Comment by HanzHaxors** [comment]
nope i havent, i don't have GUI based linux except VMs

**Comment by HanzHaxors** [comment]
Currently, this pull is irrelevant with the project aimings, closing PR.

**Comment by TheSpeedX** [comment]
@HanzHaxors  It would be great to see the GUI in a new branch. 
It would be great if you send the PR again to GUI branch.

**Comment by HanzHaxors** [comment]
👍🏽

**Pull request merged**
