### PR TITLE
Minor Fixes and Revision Pump

### PR DESCRIPTION
**Pull request by HanzHaxors**
## Addition:
 
- `-u` command line argument
- Input and output type identifier (in front of text)
- Update option to pick in the menu ("url" variable doesnt exist has been FIXED)
- Exception for non-existed selection (in menu)

## Fixes:
- Fixed glitchy WhatScraper ASCII title (tested on WSL, Kali Linux, Windows 10)

## Summary:
With merging this PR, you should bump the Minor Version once and Revision once.

### CODE REVIEW

**Comment by TheSpeedX** [comment]
Thanks for your great contribution and making the code better.

I will test it on some more platforms and merge  it.
- [ ] Ubuntu
- [ ] Termux
- [x] Windows
- [x] WSL
- [x] Kali Linux

Checking these platforms as you had already tested:  WSL, Kali Linux, Windows 10

**Comment by HanzHaxors** [comment]
i can test on those platforms too, so i will tell you the result of it. Im active in GitHub btw.

**Comment by HanzHaxors** [comment]
## Termux Test

LAYOUT PROBLEM: Whatscraper title seems to broke when termux user use portrait device retation, including menu.
CONNECTION PROBLEM (?): `google` python package seems to have some problem on it (not really sure if its only in my end)

**Comment by HanzHaxors** [comment]
## Ubuntu Test
Tested on Ubuntu 20.04.1 LTS (Focal Fossa)

No problem occurs.

**Comment by HanzHaxors** [comment]
## Termux Test #2

~~LAYOUT PROBLEM: Whatscraper title seems to broke when termux user use portrait device retation, including menu.~~
**FIXED:**
#### Portrait
[Portrait Layout](#6 )
#### Landscape
[Landscape Layout](#6 )

~~CONNECTION PROBLEM (?): google python package seems to have some problem on it (not really sure if its only in my end)~~
**FIXED, it's only in my end**

**Comment by TheSpeedX** [comment]
Thanks, Merging it

**Pull request merged**
